using DumpFormatter.Formatters;
using DumpFormatter.Model;

using System.CommandLine;
using System.Text;
using System.Text.Json;

namespace DumpFormatter;

internal static class Program
{
    enum Format
    {
        PlainText,
        Html,
        Xsd,
    }
    
    static int Main(string[] args)
    {
        var dictionary = new Option<FileInfo?>(new[] { "--dictionary", "-d" }, "The dictionary file used to translate hashes back to text.");
        var format = new Argument<Format>("format", "The dump output format.");
        var input = new Argument<FileInfo>("input", "The input JSON dump file.");
        var output = new Argument<FileInfo>("output", "The output formatted dump file.");

        var root = new RootCommand("Format a RAGE parser dump generated by DumpStructs.asi.")
        {
            dictionary,
            format, input, output,
        };
        root.SetHandler(EntryPoint, dictionary, format, input, output);
        return root.Invoke(args);
    }

    static void EntryPoint(FileInfo? dictionary, Format format, FileInfo input, FileInfo output)
    {
        Console.WriteLine($"Dictionary: {dictionary?.ToString() ?? "none"}");
        Console.WriteLine($"Format: {format}");
        Console.WriteLine($"Input:  {input}");
        Console.WriteLine($"Output: {output}");

        if (dictionary != null)
        {
            Joaat.LoadDictionary(dictionary.FullName);
        }

        ParDump dump;
        var opt = new JsonSerializerOptions(JsonSerializerDefaults.Web);
        using (var inputStream = input.OpenRead())
        {
            dump = JsonSerializer.Deserialize<ParDump>(inputStream, opt) ?? throw new ArgumentException($"JSON deserialization of '{input.FullName}' returned null");
        }
        
        IDumpFormatter formatter = format switch
        {
            Format.PlainText => new PlainTextFormatter(),
            Format.Html => new HtmlFormatter(),
            Format.Xsd => new XsdFormatter(),
            _ => throw new ArgumentException($"Unknown format '{format}'"),
        };
        
        using (var outputStream = output.OpenWrite())
        {
            using var outputWriter = new StreamWriter(outputStream, Encoding.UTF8);
            formatter.Format(outputWriter, dump);
        }
    }
}
